### ISSUE TITLE
Pages needed for editing/deleting events/groups; need more knowledge of React

### ISSUE THREAD

**Issue by AlyxReckahn** [jaredmario108/COP4331LargeProject#25]
As said above; when an event's host or a group's admin views its page, they should be able to click a button to go to a page to edit/delete the group/event. It should look a lot like the create new event/group button, but with some extra buttons and the fields all prefilled with the group/event's data. Unfortunately, I'm not sure how to do that with textboxes in React (in JS, you can just do getElementById("textbox").value = "blah", but not sure for React); can someone look into that?

**Comment by jaydensipe** [comment]
Added in 5bc459e1bc3592e7d693176503f913fcbbe7644e, c5ff6a4dd6dec77ce3c6df28c9fe2014d44d1914, e8de7b941e3801c0493e57ae612e18e4bd566ecd
