### ISSUE TITLE
Figure out how to extract item ID from URL?

### ISSUE THREAD

**Issue by AlyxReckahn** [jaredmario108/COP4331LargeProject#26]
One major point we have to overcome is that in order to have a distinct page for each event/group, we need to be able to put its ID at the end of the URL (like get2gather.com/events/14263599), and then pull the ID from the URL in order to fill out the page. We need to look more into React Router in order to do this; who wants to do so or ask Leinecker in office?

**Comment by jaydensipe** [comment]
We figured this out! 🎉
