### ISSUE TITLE
Add comments functionality to Events collection

### ISSUE THREAD

**Issue by AlyxReckahn** [jaredmario108/COP4331LargeProject#30]
A new collection is needed in the database for the commenting functionality; each entry will include an event ID, a user ID of the commenter, a string for the comment's text, and the date the comment was made.

This will also require 2 APIs; one will put a comment into the database, while another will retrieve all the comments for a given event (and sort them by date if possible).

**Comment by AlyxReckahn** [comment]
Actually, we don't need a whole new collection for comments; each event can just have a comments attribute to hold the comments. This attribute holds an array of JSON objects, each of which has a user, text, and time posted. We can pull this while loading up the event's data, and then add any new comments to the end of the array.

**Comment by jaydensipe** [comment]
Done!
