### ISSUE TITLE
(LOW PRIO, Leinecker won't notice) Data integrity issues on deleting group

### ISSUE THREAD

**Issue by AlyxReckahn** [jaredmario108/COP4331LargeProject#33]
Basically, first, if a group is deleted, any events that belonged to that group will have group ID numbers that are invalid.
Second, if a group is edited so an admin is removed while hosting events under that group, they will be hosting events under a group they aren't an admin of.

We could fix these issues by either deleting the affected events, or setting them to have no group; I would recommend the first solution for the first problem and the second for the second.

**Comment by jaydensipe** [comment]
Andddddddddddd, done.
