### ISSUE TITLE
CRITICAL: addgroup API needs to accept admin and member lists!!!

### ISSUE THREAD

**Issue by AlyxReckahn** [jaredmario108/COP4331LargeProject#35]

**Comment by AlyxReckahn** [comment]
To clarify, the makeGroup API should accept a title, description, image, and lists of adnims and members, and put that exactly int the entry in the database. We need to figure out if we'll handle the users as just IDs, or objects with IDs and names. The other APIs will also likely require fixing.

**Comment by AlyxReckahn** [comment]
Also, a number of things would be easier if we stored the user's login/username in the JWT along with the other stuff.

**Comment by brown-jh** [comment]
Fixed sometime in the last 150 commits!
