### ISSUE TITLE
Events can be deleted without verification

### ISSUE THREAD

**Issue by brown-jh** [jaredmario108/COP4331LargeProject#4]
Events have no 'CreatedBy' attribute, so there is no way to verify that whoever deletes an event should be able to.

**Comment by AlyxReckahn** [comment]
@brown-jh Would it be acceptable for an event created for a group to be deletable by any admin in that group?

**Comment by brown-jh** [comment]
@AlyxReckahn Unsure - just because somebody is an admin doesn't mean that the creator wants to give them the ability to delete the group if they so desired. Maybe it is easier to just check that they're in the admin list though.

**Comment by AlyxReckahn** [comment]
@brown-jh Wait, are we talking about deleting an event or a group? I assume that a group’s admins are going to work together closely, and any event will involve everyone in the group (hence the group), so any admin should be able to work with things like that. Plus, as you mention, just checking for an admin is the simplest possibility (compared to a “only the maker” /“all admins” option or letting them manually enter names), it should work well enough, and Leinecker probably won’t poke around that deep.

**Comment by jaydensipe** [comment]
Think this is done... :]
