### ISSUE TITLE
User can login with blank username and password

### ISSUE THREAD

**Issue by jaydensipe** [jaredmario108/COP4331LargeProject#6]
When logging in, a user can enter an empty login/password and log in. Perhaps block this or delete empty user from database

**Comment by brown-jh** [comment]
Successfully login with a blank username and password? Or that we will allow an attempted login with a missing parameter?

**Comment by brown-jh** [comment]
May be both, should be impossible to login without existing in the database.

**Comment by jaydensipe** [comment]
Right now if you hit login without entering username/password you'll log in as a blank user

**Comment by jaydensipe** [comment]
> Successfully login with a blank username and password? Or that we will allow an attempted login with a missing parameter?

Right now if you hit login without entering username/password you'll log in as a blank user

**Comment by jaydensipe** [comment]
Fixed in d933d7741cae14eeddf9ab28aa0b478d27a699df
